apiVersion: apps/v1
kind: Deployment
metadata:
  name: construction-equipment-rent-web
spec:
  selector:
    matchLabels:
      app: construction-equipment-rent-web
  replicas: 1
  template:
    metadata:
      labels:
        app: construction-equipment-rent-web
    spec:
      containers:
      - name: construction-equipment-rent-web
        image: localhost:5000/construction-equipment-rent.web
        ports:
        - name: http
          containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Live
        - name: "Api__BaseUrl"
          value: "${apiBaseUrl}/api"
---
apiVersion: v1
kind: Service
metadata:
  name: construction-equipment-rent-web
spec:
  selector:
    app: construction-equipment-rent-web
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer